// An object that know all the ALLOWED ACTION TYPES
// ~ contract or standard
const ActionTypes = {
	// Category
	CATEGORIES_ALL_REQ: 'CATEGORIES_ALL_REQ',
	CATEGORIES_ALL_OK: 'CATEGORIES_ALL_OK',
	CATEGORIES_ALL_X: 'CATEGORIES_ALL_X',

	CATEGORY_ADD_REQ: 'CATEGORY_ADD_REQ',
	CATEGORY_ADD_OK: 'CATEGORY_ADD_OK',
	CATEGORY_ADD_X: 'CATEGORY_ADD_X',

	CATEGORY_DELETE_REQ: 'CATEGORY_DELETE_REQ',
	CATEGORY_DELETE_OK: 'CATEGORY_DELETE_OK',
	CATEGORY_DELETE_X: 'CATEGORY_DELETE_X',

	CATEGORIES_FILTER_REQ: 'CATEGORIES_EXPENSIVE_REQ',
	CATEGORIES_FILTER_OK: 'CATEGORIES_EXPENSIVE_OK',
	CATEGORIES_FILTER_X: 'CATEGORIES_EXPENSIVE_X',

	//CATEGORY_RANDOMIZED_REQ:   'CATEGORY_RANDOMIZED_REQ',
	//CATEGORY_RANDOMIZED_OK:    'CATEGORY_RANDOMIZED_OK',
	//CATEGORY_RANDOMIZED_X:     'CATEGORY_RANDOMIZED_X',

	//CATEGORY_CURRENT_RESET:    'CATEGORY_CURRENT_RESET',
};

export default ActionTypes;